######################################################################
# Automatically generated by qmake (2.01a) Thu May 29 13:02:14 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Controller.hxx Model.hxx View.hxx
SOURCES += GUI.cxx
